### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [Mouloutouf/Prototype-Abahb#1]
Hello, <br/> <br/>I'm the creator of the Nice Vibrations asset, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. <br/>After that delay Github will take that repo down. <br/> <br/>Thanks, <br/>Renaud

**Comment by Mouloutouf** [comment]
Hello Renaud,

Thanks for reaching out to me. I'm sorry I did not put the repo private.
I'm fixing this right now.

Sorry for the inconvenience once again,

Max.

Le mer. 16 juin 2021 à 20:19, Renaud Forestié ***@***.***> a
écrit :

**Comment by Mouloutouf** [comment]
Hey Renaud,

I just changed the repo private. Thanks for the heads up. I do not necessarily check what plugins I use in open repos, unfortunately.

Regards,
Max.
